/**
 * Collection definitions — which entity directories this site has (members,
 * designers, printer owners, listings…), what fields their profiles carry,
 * and whether users can join them at registration.
 *
 * GENERATED BY EXORI on scripted builds: the build pipeline overwrites the
 * `collections` array below from the project's build manifest. Everything
 * else (types, helpers) is template code — extend the array by hand in a
 * standalone checkout, but never rename the exports.
 *
 * All directory pages, seeds, and profile forms are driven by this config +
 * the single generic `CollectionEntry` Prisma model. Adding a collection is a
 * config change, not a schema change.
 */

export type CollectionFieldType = "text" | "textarea" | "url" | "email" | "phone" | "tags";

export type CollectionField = {
  /** Key inside CollectionEntry.fields (camelCase). */
  name: string;
  label: string;
  type: CollectionFieldType;
  required?: boolean;
};

export type CollectionDef = {
  /** URL segment and CollectionEntry.collection value (kebab-case). */
  id: string;
  /** Plural display name — directory headline ("Designers"). */
  label: string;
  /** Singular display name — profile pages ("Designer"). */
  singular: string;
  /** One-liner shown under the directory headline. */
  description: string;
  /** Users may create their own entry in this collection (profile). */
  registerable: boolean;
  fields: CollectionField[];
};

export const collections: CollectionDef[] = [
  {
    id: "members",
    label: "Members",
    singular: "Member",
    description: "The people who make this community what it is.",
    registerable: true,
    fields: [
      { name: "headline", label: "Headline", type: "text" },
      { name: "location", label: "Location", type: "text" },
      { name: "website", label: "Website", type: "url" },
      { name: "specialties", label: "Specialties", type: "tags" },
    ],
  },
]

export function getCollection(id: string): CollectionDef | undefined {
  return collections.find((c) => c.id === id)
}
